version: '3.8'

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: rey-arrecife-pocketbase-dev
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_hooks:/pb_hooks:ro
    environment:
      - DEV_MODE=true
